language: node_js
node_js:
- 8.10.0
services:
- mongodb
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Ro3hFbH8mpy5CC178jSLLICxCIqnUCUMexZ9UMxwWns4y8CqO3AqQRHcaA3isqhkwhMSJINpwrQShs5xxzWrjqf5URCEp+5v1nXjgu41wlMt/c1xv7mAFWOxIEjV9X7acVsKMOyaECQmZmaAXvZmtAbfy8dyT2InJYDFa0TG9FKFt7WhJ0ds7RH1ShjG96vp6SDjfN3jV5ywCPagthizDhDYZX3q/u/Fu4r+LQDkIArL1c2MjtEpWBDeCMVoZ793/A5XVn08B6CP8nvEE1FMBUY5B5nPk43FINWf5BoQ4PXbAFkg4xY2H73edTLjUcrcR91/QsvRqpAfJQdl1dGUrnSHztakh1+WYiqZxKPc+y73HeRjI+vrEXn4dbukONRVKQ0DFb4Jl2qV63RNbKWER5Zhf20VXCY37HpOPS5iS2rWVvNNbqEMBaJnCRNAQqFF8AGTYc+cibRUwUo2IE3r/2salnSmhnCAd8ss7IRf2wY88IDW4bdjO/okLHpINWLCrHhcvSw43YVhyWb6RWFk9GHGMIxvgZLDIZ/J19kFzyrl4m1pXHBV31h8XXnropgTwJhaNYDM8BznrP9SZOF1rHQ7zgdZWY0MmUZ/lc4HszKr66dFzs6UT0UradJ8IgJYwZxpSrNbbMcUvQjRg+9OZ630pZXauCmptlUrYa5pRCk=
  app: pawlist-api
  on:
    repo: russellkoons/pawlist-api
